// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace jejeje.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Juegos", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desarrollador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripción")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Género")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plataforma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Portada")
                        .HasColumnType("TEXT");

                    b.Property<string>("plataformaID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("plataformaID");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("Personajes", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Habilidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nivel")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("juegosid")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("juegosid");

                    b.ToTable("personajes");
                });

            modelBuilder.Entity("Plataformas", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("icono")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("plataformas");
                });

            modelBuilder.Entity("Juegos", b =>
                {
                    b.HasOne("Plataformas", "plataforma")
                        .WithMany("juegos")
                        .HasForeignKey("plataformaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plataforma");
                });

            modelBuilder.Entity("Personajes", b =>
                {
                    b.HasOne("Juegos", "juego")
                        .WithMany("personajes")
                        .HasForeignKey("juegosid");

                    b.Navigation("juego");
                });

            modelBuilder.Entity("Juegos", b =>
                {
                    b.Navigation("personajes");
                });

            modelBuilder.Entity("Plataformas", b =>
                {
                    b.Navigation("juegos");
                });
#pragma warning restore 612, 618
        }
    }
}
